### ISSUE TITLE
Doesn't build with yaml-cpp 0.6.0

### ISSUE THREAD

**Issue by hobbes1069** [AcademySoftwareFoundation/OpenColorIO#517]
Attempted build on Fedora Rawhide with GCC 8 preview:

`
[ 73%] Linking CXX executable ocio_core_tests
cd /builddir/build/BUILD/OpenColorIO-1.1.0/build/src/core_tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/ocio_core_tests.dir/link.txt --verbose=1
/usr/bin/c++  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -Wall -Wextra -Wshadow -Wconversion -Wcast-qual -Wformat=2 -msse2 -O2 -g -DNDEBUG  -Wl,-z,relro  -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -rdynamic CMakeFiles/ocio_core_tests.dir/__/core/AllocationOp.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/AllocationTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Baker.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/CDLTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Caching.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/ColorSpace.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/ColorSpaceTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Config.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Context.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Display.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/DisplayTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Exception.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/ExponentOps.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/ExponentTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormat3DL.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatCC.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatCCC.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatCDL.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatCSP.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatHDL.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatIridasCube.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatIridasItx.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatIridasLook.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatPandora.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatSpi1D.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatSpi3D.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatSpiMtx.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatTruelight.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileFormatVF.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/FileTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/GpuShaderDesc.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/GpuShaderUtils.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/GroupTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/HashUtils.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/ImageDesc.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/ImagePacking.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/LogOps.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/LogTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Logging.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Look.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/LookParse.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/LookTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Lut1DOp.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Lut3DOp.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/MathUtils.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/MatrixOps.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/MatrixTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/NoOps.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/OCIOYaml.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Op.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/OpOptimizers.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/ParseUtils.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/PathUtils.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Platform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Processor.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/ScanlineHelper.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/Transform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/TruelightOp.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/TruelightTransform.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/UnitTest.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/md5/md5.cpp.o CMakeFiles/ocio_core_tests.dir/__/core/pystring/pystring.cpp.o  -o ocio_core_tests -ltinyxml -lyaml-cpp 
make[2]: Leaving directory '/builddir/build/BUILD/OpenColorIO-1.1.0/build'
CMakeFiles/ocio_core_tests.dir/__/core/OCIOYaml.cpp.o: In function `YAML::Exception::Exception(YAML::Mark const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/yaml-cpp/exceptions.h:122: undefined reference to `vtable for YAML::Exception'
CMakeFiles/ocio_core_tests.dir/__/core/OCIOYaml.cpp.o: In function `YAML::RepresentationException::RepresentationException(YAML::Mark const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/yaml-cpp/exceptions.h:155: undefined reference to `vtable for YAML::RepresentationException'
CMakeFiles/ocio_core_tests.dir/__/core/OCIOYaml.cpp.o: In function `YAML::Exception::Exception(YAML::Mark const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/yaml-cpp/exceptions.h:122: undefined reference to `vtable for YAML::Exception'
CMakeFiles/ocio_core_tests.dir/__/core/OCIOYaml.cpp.o: In function `YAML::RepresentationException::RepresentationException(YAML::Mark const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/yaml-cpp/exceptions.h:155: undefined reference to `vtable for YAML::RepresentationException'
CMakeFiles/ocio_core_tests.dir/__/core/OCIOYaml.cpp.o: In function `YAML::Exception::Exception(YAML::Mark const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/yaml-cpp/exceptions.h:122: undefined reference to `vtable for YAML::Exception'
CMakeFiles/ocio_core_tests.dir/__/core/OCIOYaml.cpp.o: In function `YAML::RepresentationException::RepresentationException(YAML::Mark const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/yaml-cpp/exceptions.h:155: undefined reference to `vtable for YAML::RepresentationException'
/usr/bin/ld: ocio_core_tests: hidden symbol `_ZTVN4YAML9ExceptionE' isn't defined
/usr/bin/ld: final link failed: Bad value
`

**Comment by svenstaro** [comment]
I can reproduce the same error with current master OCIO and yaml-cpp 0.6.1.

**Comment by hobbes1069** [comment]
I disabled tests and get a similar error while linking the main library, but it's not QUITE the same:

`
[ 63%] Linking CXX shared library libOpenColorIO.so
cd /builddir/build/BUILD/OpenColorIO-1.1.0/build/src/core && /usr/bin/cmake -E cmake_link_script CMakeFiles/OpenColorIO.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -Wall -Wextra -Wshadow -Wconversion -Wcast-qual -Wformat=2 -msse2 -O2 -g -DNDEBUG -Wl,-z,relro  -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -shared -Wl,-soname,libOpenColorIO.so.1 -o libOpenColorIO.so.1.1.0 CMakeFiles/OpenColorIO.dir/AllocationOp.cpp.o CMakeFiles/OpenColorIO.dir/AllocationTransform.cpp.o CMakeFiles/OpenColorIO.dir/Baker.cpp.o CMakeFiles/OpenColorIO.dir/CDLTransform.cpp.o CMakeFiles/OpenColorIO.dir/Caching.cpp.o CMakeFiles/OpenColorIO.dir/ColorSpace.cpp.o CMakeFiles/OpenColorIO.dir/ColorSpaceTransform.cpp.o CMakeFiles/OpenColorIO.dir/Config.cpp.o CMakeFiles/OpenColorIO.dir/Context.cpp.o CMakeFiles/OpenColorIO.dir/Display.cpp.o CMakeFiles/OpenColorIO.dir/DisplayTransform.cpp.o CMakeFiles/OpenColorIO.dir/Exception.cpp.o CMakeFiles/OpenColorIO.dir/ExponentOps.cpp.o CMakeFiles/OpenColorIO.dir/ExponentTransform.cpp.o CMakeFiles/OpenColorIO.dir/FileFormat3DL.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatCC.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatCCC.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatCDL.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatCSP.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatHDL.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatIridasCube.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatIridasItx.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatIridasLook.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatPandora.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatSpi1D.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatSpi3D.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatSpiMtx.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatTruelight.cpp.o CMakeFiles/OpenColorIO.dir/FileFormatVF.cpp.o CMakeFiles/OpenColorIO.dir/FileTransform.cpp.o CMakeFiles/OpenColorIO.dir/GpuShaderDesc.cpp.o CMakeFiles/OpenColorIO.dir/GpuShaderUtils.cpp.o CMakeFiles/OpenColorIO.dir/GroupTransform.cpp.o CMakeFiles/OpenColorIO.dir/HashUtils.cpp.o CMakeFiles/OpenColorIO.dir/ImageDesc.cpp.o CMakeFiles/OpenColorIO.dir/ImagePacking.cpp.o CMakeFiles/OpenColorIO.dir/LogOps.cpp.o CMakeFiles/OpenColorIO.dir/LogTransform.cpp.o CMakeFiles/OpenColorIO.dir/Logging.cpp.o CMakeFiles/OpenColorIO.dir/Look.cpp.o CMakeFiles/OpenColorIO.dir/LookParse.cpp.o CMakeFiles/OpenColorIO.dir/LookTransform.cpp.o CMakeFiles/OpenColorIO.dir/Lut1DOp.cpp.o CMakeFiles/OpenColorIO.dir/Lut3DOp.cpp.o CMakeFiles/OpenColorIO.dir/MathUtils.cpp.o CMakeFiles/OpenColorIO.dir/MatrixOps.cpp.o CMakeFiles/OpenColorIO.dir/MatrixTransform.cpp.o CMakeFiles/OpenColorIO.dir/NoOps.cpp.o CMakeFiles/OpenColorIO.dir/OCIOYaml.cpp.o CMakeFiles/OpenColorIO.dir/Op.cpp.o CMakeFiles/OpenColorIO.dir/OpOptimizers.cpp.o CMakeFiles/OpenColorIO.dir/ParseUtils.cpp.o CMakeFiles/OpenColorIO.dir/PathUtils.cpp.o CMakeFiles/OpenColorIO.dir/Platform.cpp.o CMakeFiles/OpenColorIO.dir/Processor.cpp.o CMakeFiles/OpenColorIO.dir/ScanlineHelper.cpp.o CMakeFiles/OpenColorIO.dir/Transform.cpp.o CMakeFiles/OpenColorIO.dir/TruelightOp.cpp.o CMakeFiles/OpenColorIO.dir/TruelightTransform.cpp.o CMakeFiles/OpenColorIO.dir/UnitTest.cpp.o CMakeFiles/OpenColorIO.dir/md5/md5.cpp.o CMakeFiles/OpenColorIO.dir/pystring/pystring.cpp.o -ltinyxml -lyaml-cpp 
make[2]: Leaving directory '/builddir/build/BUILD/OpenColorIO-1.1.0/build'
CMakeFiles/OpenColorIO.dir/OCIOYaml.cpp.o: In function `YAML::Exception::Exception(YAML::Mark const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/yaml-cpp/exceptions.h:122: undefined reference to `vtable for YAML::Exception'
/usr/bin/ld: CMakeFiles/OpenColorIO.dir/OCIOYaml.cpp.o: relocation R_X86_64_PC32 against undefined hidden symbol `_ZTVN4YAML9ExceptionE' can not be used when making a shared object
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
`

**Comment by kkofler** [comment]
An undefined reference to the `vtable` typically means that you are declaring a virtual method without actually defining it. g++ can then (based on factors that only the compiler authors really understand) decide to pick that method as the key method for emitting the `vtable` and you are out of luck. So fix that: any declared virtual method **must** be implemented.

**Comment by kkofler** [comment]
The whole block from https://github.com/imageworks/OpenColorIO/blob/master/src/core/OCIOYaml.cpp#L33 to https://github.com/imageworks/OpenColorIO/blob/master/src/core/OCIOYaml.cpp#L68 must go away. It breaks system `yaml-cpp` usage.

This only worked by accident before, because the key methods for the vtables were inline. That was fixed in https://github.com/jbeder/yaml-cpp/commit/0f20ddcdcb264d054191d66c5c02a9b7bd2e86a1, so now the vtable can only be found if the visibility is sane. Hardcoding hidden visibility for these classes breaks it.

**Comment by AdamWill** [comment]
For the record, this whole block declaring the visibility as hidden was introduced in https://github.com/imageworks/OpenColorIO/commit/c5c391c1d6af798a5f2f9b80a4b03c98f5a45de7 . That looks like it's about fixing some issue in the case when *not* building against system yaml-cpp, but we need a way that works properly in both cases.

**Comment by Lucretia** [comment]
@kkofler I just commented that out on media-libs/opencolorio-1.1.0-r1 on gentoo and it built fine,with those lines there it failed.

**Comment by pdvrieze** [comment]
Let me guess. The original issue when not using the system library was symbol collision. Private versions of libraries should not pretend to be the public ones. You should adapt the private version to not expose symbols and versioned symbols with a private version if you don't just use a separate/different namespace entirely (you can use defines to make this transparent). Even versioned symbols don't work that great as they only work if both version are versioned.

**Comment by kkofler** [comment]
Your merge does **not** fix this issue. The offending code block is still present at https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/OpenColorIO/OCIOYaml.cpp#L10

**Comment by kkofler** [comment]
You upgraded the bundled yaml-cpp to 0.6.x, but the build against the system yaml-cpp 0.6.x is still broken and will remain broken as long as those forward declarations are present.

**Comment by hodoulp** [comment]
My intent was not close the issue (github automatically did it). I only mentioned it in my pull request waiting one of you to close or not the issue.

**Comment by hodoulp** [comment]
On ubuntu 19 with gcc 8.3 & clang 8.0, the build (including the Yaml 0.6.3 build) succeeds.

**Comment by hodoulp** [comment]
Using ubuntu 19 and gcc 8:
1. No yaml installed, the build download Yaml 0.6.3 and successfully builds.
2. Compile & install yaml 0.6.3, OCIO build failed to detect Yaml so it downloads Yaml 0.6.3 and successfully builds.

The second use case is faulty as the right yaml is installed. Next week I will investigate that.

Does someone know how to 'find' the Yaml version from headers?

**Comment by kkofler** [comment]
Try `apt-get install libyaml-cpp-dev` instead of compiling it yourself.

**Comment by hodoulp** [comment]
By hacking the cmake files to use the installed yaml, the build fails and removing the problematic lines, fixes it. I tried with a 'compiled & installed' Yaml and with `apt-get install libyaml-cpp-dev`.

**Comment by hodoulp** [comment]
I was not able to find a reliable way to correctly detect the Yaml version. Only the Yaml 0.6.3 could be correctly detected (i.e. the file `include/yaml-cpp/noncopyable.h` is removed from 0.6.3 versus 0.6.2). So, the detection is only reliable for 0.3.0 and 0.6.3. That's enough for OCIO v2 which expects to use the latest version. 

Note that the `apt-get install libyaml-cpp-dev` installs Yaml 0.6.0 on Ubuntu so the OCIO build still downloads 0.6.3 and compiles it. That behavior could also happen on other Linux flavors.

A pull request removing the legacy forward declarations plus other minor changes will soon be ready.
