### ISSUE TITLE
OpenColorIO doesn't build with the new minizip-ng 4.0.1 version

### ISSUE THREAD

**Issue by ljavorsk** [AcademySoftwareFoundation/OpenColorIO#1856]
I've tried to rebased the minizip-ng to version 4.0.1 and rebuild all of the packages that depends on it's libminizip.so library.
I was rebuilding it in the private COPR project (on Fedora Rawhide)

However, OpenColorIO fails to build with this new version.

Here is a snippet of the errors in the build:

> /builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp:228:25: error: too many arguments to function â€˜void* mz_stream_mem_create()â€™
  228 |     mz_stream_mem_create(&write_mem_stream);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from /builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp:24:
/usr/include/minizip/mz_strm_mem.h:37:9: note: declared here
   37 | void*   mz_stream_mem_create(void);
      |         ^~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp:240:25: error: too many arguments to function â€˜void* mz_zip_writer_create()â€™
  240 |     mz_zip_writer_create(&archiver);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp:29:
/usr/include/minizip/mz_zip_rw.h:264:9: note: declared here
  264 | void*   mz_zip_writer_create(void);
      |         ^~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp: In function â€˜void OpenColorIO_v2_2::ExtractOCIOZArchive(const char*, const char*)â€™:
/builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp:335:25: error: too many arguments to function â€˜void* mz_zip_reader_create()â€™
  335 |     mz_zip_reader_create(&extracter);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/usr/include/minizip/mz_zip_rw.h:146:9: note: declared here
  146 | void*   mz_zip_reader_create(void);
      |         ^~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp: In function â€˜std::vector<unsigned char> OpenColorIO_v2_2::getFileStringFromArchiveFile(const std::string&, const std::string&, std::vector<unsigned char> (*)(void*, mz_zip_file&, std::string))â€™:
/builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp:453:25: error: too many arguments to function â€˜void* mz_zip_reader_create()â€™
  453 |     mz_zip_reader_create(&reader);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/usr/include/minizip/mz_zip_rw.h:146:9: note: declared here
  146 | void*   mz_zip_reader_create(void);
      |         ^~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp: In function â€˜void OpenColorIO_v2_2::getEntriesMappingFromArchiveFile(const std::string&, std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)â€™:
/builddir/build/BUILD/OpenColorIO-2.2.1/src/OpenColorIO/OCIOZArchive.cpp:513:25: error: too many arguments to function â€˜void* mz_zip_reader_create()â€™
  513 |     mz_zip_reader_create(&reader);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/usr/include/minizip/mz_zip_rw.h:146:9: note: declared here
  146 | void*   mz_zip_reader_create(void);
      |         ^~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [src/OpenColorIO/CMakeFiles/OpenColorIO.dir/build.make:1017: src/OpenColorIO/CMakeFiles/OpenColorIO.dir/OCIOZArchive.cpp.o] Error 1

The full build is here: https://download.copr.fedorainfracloud.org/results/ljavorsk/minizip-ng/fedora-rawhide-x86_64/06403669-OpenColorIO/builder-live.log.gz

Do you have any idea what could be causing this error? Thank you for the response.

**Comment by ljavorsk** [comment]
My bad, it looks like it is there (https://github.com/AcademySoftwareFoundation/OpenColorIO/commit/bdc4cd124140f997cdec1c5d7db72b1550fe7eac), only Fedora didn't rebase yet.
