### ISSUE TITLE
Build error with python 3.7

### ISSUE THREAD

**Issue by VVD** [AcademySoftwareFoundation/OpenColorIO#1023]
FreeBSD 12.1 amd64.
With DOCS option OFF build fine with python 3.7 and python 2.7.
But with DOCS option ON build fine with python 2.7 only. With 3.7 I got error and search didn't help.
Build log:
```
-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting Build Type to: Release
-- Setting Namespace to: OpenColorIO
-- Exec prefix not specified, defaulting to /usr/local
-- Use Boost Ptr: OFF
-- Setting python bin to: /usr/local/bin/python3.7
Python library: PYTHON_LIBRARY-NOTFOUND
-- Setting EXTDIST_BINPATH: /tmp/work/usr/ports/graphics/opencolorio/work/.build/ext/dist/bin
-- Setting EXTDIST_PYTHONPATH: /tmp/work/usr/ports/graphics/opencolorio/work/.build/ext/dist/lib/python3.7/site-packages
-- Found TinyXML: /usr/local/lib/libtinyxml.so  
-- TinyXML version: 2.6.2
-- External TinyXML will be used.
-- Found PkgConfig: pkgconf (found version "1.6.3") 
-- Found yaml-cpp: /usr/local/lib/libyaml-cpp03.so  
-- Generate Documentation: true
-- Create sphinx conf.py from conf.py.in
-- Copying doc to staging area
-- Copy extra doc files to staging area
-- Extracting .rst files from C++ headers
-- SSE Optimizations: ON
-- Could NOT find Truelight (missing: Truelight_INCLUDE_DIR Truelight_LIBRARIES Truelight_LIBRARY_DIR) 
-- Not building truelight transform support. Add the flag -D TRUELIGHT_INSTALL_PATH=... or set the TRUELIGHT_ROOT environment variable
-- Create OpenColorABI.h from OpenColorABI.h.in
-- Setting OCIO SOVERSION to: 1
-- Create OpenColorIO.pc from OpenColorIO.pc.in
-- Build Unit Tests: ON
-- Create ocio_core_tests.sh.in from ocio_core_tests.sh
-- Disable build of apps. See cmake options : OCIO_BUILD_APPS and OCIO_BUILD_SHARED/OCIO_BUILD_STATIC (requiered)
-- Python library to include 'lib' prefix: OFF
-- Python 3.7 okay (UCS: ucs4), will build the Python bindings against /usr/local/include/python3.7m
-- Python variant path is lib/python3.7/site-packages
-- Found PythonLibs: /usr/local/lib/libpython3.7m.so (found version "3.7.7") 
PYTHON_VARIANT_PATH: lib/python3.7/site-packages
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_PYTHON_SUFFIX
    CMAKE_CXX_FLAGS_DEBUG
    CMAKE_C_FLAGS_DEBUG
    CMAKE_C_FLAGS_RELEASE
    CMAKE_VERBOSE_MAKEFILE
    THREADS_HAVE_PTHREAD_ARG


-- Build files have been written to: /tmp/work/usr/ports/graphics/opencolorio/work/.build
===>  Building for opencolorio-1.1.1_1
[1/200] cd /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs && /usr/local/bin/cmake -E make_directory /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools && /usr/local/bin/cmake -E make_directory /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools && /usr/local/bin/cmake -E make_directory /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix && /usr/local/bin/cmake -E make_directory /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/tmp && /usr/local/bin/cmake -E make_directory /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp && /usr/local/bin/cmake -E make_directory /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src && /usr/local/bin/cmake -E make_directory /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp && /usr/local/bin/cmake -E touch /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/setuptools-mkdir
[2/200] cd /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src && /usr/local/bin/cmake -P /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/verify-setuptools.cmake && /usr/local/bin/cmake -P /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/extract-setuptools.cmake && /usr/local/bin/cmake -E touch /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/setuptools-download
CMake Warning at setuptools-stamp/verify-setuptools.cmake:15 (message):
  File will not be verified since no URL_HASH specified


-- extracting...
     src='/tmp/work/usr/ports/graphics/opencolorio/work/OpenColorIO-1.1.1/ext/setuptools-1.1.6.tar.gz'
     dst='/tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[3/200] cd /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs && /usr/local/bin/cmake -E echo_append && /usr/local/bin/cmake -E touch /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/setuptools-update
[4/200] cd /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs && /usr/local/bin/cmake -E echo_append && /usr/local/bin/cmake -E touch /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/setuptools-patch
[5/200] cd /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools && /usr/local/bin/cmake -E make_directory /tmp/work/usr/ports/graphics/opencolorio/work/.build/ext/dist/lib/python3.7/site-packages && /usr/local/bin/cmake -E touch /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/setuptools-configure
[6/200] cd /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools && PYTHONPATH=/tmp/work/usr/ports/graphics/opencolorio/work/.build/ext/dist/lib/python3.7/site-packages: /usr/local/bin/python3.7 setup.py build && /usr/local/bin/cmake -E touch /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/setuptools-build
FAILED: docs/setuptools-prefix/src/setuptools-stamp/setuptools-build 
cd /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools && PYTHONPATH=/tmp/work/usr/ports/graphics/opencolorio/work/.build/ext/dist/lib/python3.7/site-packages: /usr/local/bin/python3.7 setup.py build && /usr/local/bin/cmake -E touch /tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools-stamp/setuptools-build
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    exec(init_file.read(), command_ns)
  File "<string>", line 8, in <module>
  File "/tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools/setuptools/dist.py", line 16, in <module>
    import pkg_resources
  File "/tmp/work/usr/ports/graphics/opencolorio/work/.build/docs/setuptools-prefix/src/setuptools/pkg_resources.py", line 1435, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
[7/200] /usr/bin/c++  -DOpenColorIO_EXPORTS -DUSE_SSE -I/tmp/work/usr/ports/graphics/opencolorio/work/OpenColorIO-1.1.1/export -Iexport -I/tmp/work/usr/ports/graphics/opencolorio/work/OpenColorIO-1.1.1/ext/oiio/src/include -Iext/dist/include -O2 -pipe -march=core2 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -Wno-deprecated-register -isystem /usr/local/include -msse2 -O2 -pipe -march=core2 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -Wno-deprecated-register -isystem /usr/local/include -fPIC   -DOLDYAML  -fPIC -fvisibility=hidden -Werror -std=c++11 -MD -MT src/core/CMakeFiles/OpenColorIO.dir/AllocationOp.cpp.o -MF src/core/CMakeFiles/OpenColorIO.dir/AllocationOp.cpp.o.d -o src/core/CMakeFiles/OpenColorIO.dir/AllocationOp.cpp.o -c /tmp/work/usr/ports/graphics/opencolorio/work/OpenColorIO-1.1.1/src/core/AllocationOp.cpp
ninja: build stopped: subcommand failed.
```

**Comment by hodoulp** [comment]
Hi @VVD 
OCIO 1.x does not support Python 3. But the coming OCIO v2 supports both Python versions.

**Comment by hodoulp** [comment]
That's a known limitation of OCIO v1 so I close the defect.
Please feel free to reopen it if needed.

**Comment by VVD** [comment]
But it build and work with python 3.7 without DOCS…
When v2 will be released?

**Comment by hodoulp** [comment]
OCIOv2 feature complete is planned for this summer.

Note: As any open source project we are open to contributions from the community. So, you can definitively submit a pull request to fix the Python 3 support in OCIOv1 if that's a blocker for you. Refer to [CONTRIBUTING.md](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/CONTRIBUTING.md) for details.

**Comment by VVD** [comment]
Thanks. I'm not python developer and I'll wait v2.

**Comment by VVD** [comment]
Is master support python 3 already?

**Comment by VVD** [comment]
All FreeBSD ports with mandatory dependency from python 2 will be removed on 2020-12-31 if not fixed:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249695

**Comment by VVD** [comment]
There are issue already: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249534
